# version: "3.7"
version: "3.4"

services:

  mqtt-broker:
    image: eclipse-mosquitto:2.0.9
    restart: always
    # hostname: mosquitto
    # container_name: mosquitto
    # networks:
    #     - default
    # expose:
    #     - "1883"
    #     - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
      # - ./mqtt/mosquitto/data:/mosquitto/data
      # - ./mqtt/mosquitto/log:/mosquitto/log

  iot-mongodb:
    container_name: iot-mongodb
    hostname: iot-mongodb
    image: mongo:4.4-focal # mongo 5.0+ cannot run on NUC celeron
    environment:
      - MONGO_INITDB_DATABASE=ananda
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Magicalmint636
      - MONGO_REPLICA_SET_NAME=rs0
    expose:
      - 27017
    ports:
      - 27017:27017
    # volumes:
    #   # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
    #   - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    #   # - ./mongo_conf/mongod.conf:/etc/mongod.conf
    #   - ./mongo_key/replica.key:/data/replica.key
    #   - iot-mongodb-vol:/data/db
    volumes:
      - ./mongo_conf/mongod.conf:/etc/mongod.conf
      - ./initdb.d/:/docker-entrypoint-initdb.d/
      - iot-mongodb-vol:/data/db/
      - ./mongo_log/:/var/log/mongodb/
      # - ./mongo_host/hosts:/etc/hosts
      - ./mongo_key/replica.key:/data/replica.key
    
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: ["-f", "/etc/mongod.conf", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/replica.key"]
    # command: ["-f", "/etc/mongod.conf", "--replSet", "rs0", "--bind_ip", "0.0.0.0", "--keyFile", "/data/replica.key"]
    
    # entrypoint:
    #   - bash
    #   - -c
    #   - |
    #       chmod 400 /data/replica.key
    #       chown 999:999 /data/replica.key
    #       exec docker-entrypoint.sh $$@
    # command: "mongod --bind_ip_all --replSet replicaSet01 --keyFile /data/replica.key"

volumes:
  iot-mongodb-vol:
    external: true


# https://faun.pub/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3