version: '3.4'

services:
  volttron1:
    container_name: volttron1
    hostname: volttron1
    # image: eclipsevolttron/volttron:develop
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      # host_port:container_port
      # http port for volttron central
      - 8443:8443
    volumes:
      - ./platform_config.yml:/platform_config.yml
      - ./configs:/home/volttron/configs
      - volttron1-volume:/home/volttron/db
      - ./agents:/code/volttron/agents
      - ./Agents:/code/volttron/Agents
      - ./core:/startup
      - ./libraries:/home/volttron/.volttron/libraries
      - ./requirements.txt:/requirements.txt
      - ./site_configs:/code/volttron/site_configs
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine3.20
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd!
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  volttron1-volume:
    name: volttron1-data
