# Properties to be added to the root config file
# the properties should be ingestible for volttron
# the values will be presented in the config file
# as key=value
config:
  vip-address: tcp://0.0.0.0:22916
  # For rabbitmq this should match the hostname specified in
  # in the docker compose file hostname field for the service.
  bind-web-address: https://0.0.0.0:8443
  volttron-central-address: https://0.0.0.0:8443
  instance-name: volttron1
  message-bus: zmq # allowed values: zmq, rmq
  # volttron-central-serverkey: a different key

# Agents dictionary to install. The key must be a valid
# identity for the agent to be installed correctly.
agents:
  # ac:
  #   source: $VOLTTRON_ROOT/agents/AC
  #   config: $CONFIG/ac.config
  #   tag: ac
  listener:
    source: $VOLTTRON_ROOT/examples/ListenerAgent
    config: $CONFIG/listener.config
    tag: listener


  afdd:
    source: $VOLTTRON_ROOT/agents/Applications/AFDD
    config: $CONFIG/sample_config.yaml
    tag: afdd

  # data_logger:
  #   source: $VOLTTRON_ROOT/agents/DataLogger
  #   config: $CONFIG/data_logger.config
  #   tag: data_logger

  # rest:
  #   source: $VOLTTRON_ROOT/agents/REST
  #   config: $CONFIG/rest.config
  #   tag: rest

  # lifebeing:
  #   source: $VOLTTRON_ROOT/agents/Lifebeing
  #   config: $CONFIG/lifebeing.config
  #   tag: lifebeing

  # iaq:
  #   source: $VOLTTRON_ROOT/agents/IAQ
  #   config: $CONFIG/iaq.config
  #   tag: iaq