agents:
  bacnet:
    config: $VOLTTRON_ROOT/site_configs/cp9.yaml
    source: $VOLTTRON_ROOT/Agents/Devices/BACnet
    tag: bacnet
  dataintegrity:
    config: $VOLTTRON_ROOT/site_configs/cp9.yaml
    source: $VOLTTRON_ROOT/Agents/Services/DataIntegrity
    tag: dataintegrity
  gatewaystatus:
    config: $VOLTTRON_ROOT/site_configs/cp9.yaml
    source: $VOLTTRON_ROOT/Agents/Services/GatewayStatus
    tag: gatewaystatus
  mongodb:
    config: $VOLTTRON_ROOT/site_configs/cp9.yaml
    source: $VOLTTRON_ROOT/Agents/Services/MongoDB
    tag: mongodb
  platform_agent:
    config: $VOLTTRON_ROOT/site_configs/cp9.yaml
    source: $VOLTTRON_ROOT/Agents/Platforms/PlatformAgent
    tag: platform_agent
  timescaledb:
    config: $VOLTTRON_ROOT/site_configs/cp9.yaml
    source: $VOLTTRON_ROOT/Agents/Services/TimescaleDB
    tag: timescaledb
  weathertmd:
    config: $VOLTTRON_ROOT/site_configs/cp9.yaml
    source: $VOLTTRON_ROOT/Agents/Services/WeatherTMD
    tag: weathertmd
config:
  bind-web-address: https://0.0.0.0:8443
  instance-name: volttron1
  message-bus: zmq
  vip-address: tcp://0.0.0.0:22916
  volttron-central-address: https://0.0.0.0:8443
