#!/bin/bash
modbus_id=8
for room in 601 602 603 604 605 ; do
    echo $room
    /home/pi/alto_os/scripts/install-agent.py -s Agents/Room -i room_$room -t room_$room --enable --start
    sleep 1
    cat /home/pi/alto_os/Agents/Room/config_rooms | sed "s/rnumber_replace/$room/g" | sed "s/rnumber_replace/$modbus_id/g" | sed "s/^M//g" > /tmp/tbd
    vctl config store room_$room config /tmp/tbd
    sleep 1
    ((modbus_id++))
done