# persistence true
persistence false
# persistence_file mosquitto.db
# persistence_location /mosquitto/data/
# log_dest file /mosquitto/log/mosquitto.log
# log_dest stdout

allow_anonymous true
listener 1883

# listener 9001
# protocol websockets
# allow_anonymous true
# listener 9001 127.0.0.1
listener 9001 0.0.0.0
protocol websockets
