load_forecast_agent:
  model_path: "models/load_forecast_exp2_trainFromStart_testUntilEnd_trial3.pkl"
  timescaledb:
    db_name: "postgres"
    username: "alto"
    password: "Magicalmint@636"
    host: "alto-timescaledb.postgres.database.azure.com"
    port: 5432
    table: "aggregated_data_chiller"
    location: "qsncc"
  look_back_time_step:
    time_step: 168
    multiplier_to_sec: 3600
    data_resolution: "15min"
  forecast_resolution: "1H"
  prediction_horizon: 24
  cron: "15 0 * * *"
  feature_column:
    - "cooling_rate"
    - "humidity"
    - "drybulb_temperature"
  upload_inference_table: "ml_inference"
