#!/usr/bin/env python3
# Setting up MQTT for already connected Tasmota devices
import asyncio
import aiohttp as aioh
import ipaddress
import urllib

options={"SetOption3": 1,
         "MqttHost": "10.10.3.254",
         "MqttPort": 1883,
         "MqttUser":"alto",
         "Mqttpassword": "altotech",
         "WebPassword": "altotech",
         "Module": 30}
setup_param = {
    "cmnd": "Backlog "
    + ";".join([f"{x} {y}" for x, y in options.items()])
}
setup_param = urllib.parse.urlencode(setup_param, quote_via=urllib.parse.quote)
setup_param = "user=admin&password=altotech&"+setup_param
myauth = aioh.BasicAuth(login="admin", password="altotech")
nbtasks = 20

async def setup(id,queue):
    global setup_param
    global myauth
    whle True:
        ip = await queue.get()
        queue.task_done()
        if ip == "The End":
            break
        print(f"Trying {ip}")
        doitagain = True
        try:
            #async with aioh.ClientSession(auth=myauth) as session:
                #async with session.request(
                    #"get", f"http://{ip}/cm", params=setup_param
                #) as resp:
                    #print(resp.url)
                    #print("Tasmota: Response status was {}".format(resp.status))
                    #if resp.status == 401:
                        #doitagain = True
                    #elif resp.status == 200:
                        #print(f"IP {ip} was setup")
                    #else:
                        #print(f"IP {ip} could not be setup")
            if doitagain:
                async with aioh.ClientSession(auth=None) as session:
                    async with session.request(
                        "get", f"http://{ip}/cm", params=setup_param
                    ) as resp:
                        print(resp.url)
                        print(
                            "Tasmota: Response status was {}".format(resp.status)
                        )
                        if resp.status == 200:
                            print(f"IP {ip} was setup")
                        else:
                            print(f"IP {ip} could not be setup")
                            print(resp.text)
        except aioh.client_exceptions.ClientConnectorError:
            pass
        except Exception as e:
            print(f"Opps for {ip}: {e}")
    print(f"Closing {id}")
   
async def list_addr(queue):
    global nbtasks
    network = ipaddress.IPv4Network("10.10.0.0/23")
    for host in network.hosts():
        if host < ipaddress.IPv4Address("10.10.0.30"):
            continue
        if host == ipaddress.IPv4Address("10.10.1.30"):
            break
        await queue.put(host)
    for x in range(nbtasks):
        await.put("The End")
    print("Closing list_addr")
    
if __name__ == "__main__":
    
    queue = asyncio.queue(maxsize=100)
    loop = asyncio.get_event_loop()
    network = ipaddress.IPv4Network("10.10.0.0/23")
    for host in network.hosts():
        if host < ipaddress.IPv4Address("10.10.0.30"):
            continue
        if host == ipaddress.IPv4Address("10.10.1.30"):
            break
        loop.run_until_complete(asyncio.gather([list_addr(queue)]+[ setup(x,queue) for x in range(nbtasks)])
