#!/usr/bin/env python3
# Setting up MQTT for already connected Tasmota devices
import asyncio
import aiohttp as aioh
import ipaddress
import urllib

setup_param = {
    "cmnd": "Upgrade 1"
}
#setup_param = urllib.parse.urlencode(setup_param, quote_via=urllib.parse.quote)
setup_param = "user=admin&password=altotech&cmnd=Upgrade 1"
myauth = aioh.BasicAuth(login="admin", password="altotech")

async def setup(ip):
    global setup_param
    global myauth
    print(f"Trying {ip}")
    doitagain = True
    try:
        #async with aioh.ClientSession(auth=myauth) as session:
            #async with session.request(
                #"get", f"http://{ip}/cm", params=setup_param
            #) as resp:
                #print(resp.url)
                #print("Tasmota: Response status was {}".format(resp.status))
                #if resp.status == 401:
                    #doitagain = True
                    #print(resp.text)
                #elif resp.status == 200:
                    #print(f"IP {ip} was upgraded")
                    #print(resp.text)
                #else:
                    #print(f"IP {ip} could not be setup")
        if doitagain:
            async with aioh.ClientSession(auth=None) as session:
                async with session.request(
                    "get", f"http://{ip}/cm", params=setup_param
                ) as resp:
                    print(resp.url)
                    print(
                        "Tasmota: Response status was {}".format(resp.status)
                    )
                    if resp.status == 200:
                        print(f"IP {ip} was upgraded")
                    else:
                        print(f"IP {ip} could not be upgraded")
    except aioh.client_exceptions.ClientConnectorError:
        pass
    except Exception as e:
        print(f"Opps for {ip}: {e}")
        
    
if __name__ == "__main__":
    
    loop = asyncio.get_event_loop()
    network = ipaddress.IPv4Network("10.10.0.0/22")
    for host in network.hosts():
        loop.run_until_complete(setup(host))
