---
- name: Alto OS Systemd
  hosts: test_ansible_1
  become: false
  vars:
    remove_alto_run: true
    remove_volttron_service: true
    remove_firebaseproxy_service: true
    ans_root_path: /Users/oenlighteno/Documents/Alto2021/ansible/beta
  tasks:
    - name: Remove alto_run if exists
      file:
        path: ~/alto_run
        state: absent
      when: remove_alto_run|default(false)|bool
      delay: 2
      retries: 3
    - name: Remove volttron.service if exists
      become: true
      become_method: sudo
      file:
        path: /etc/systemd/system/volttron.service
        state: absent
      when: remove_volttron_service|default(false)|bool and remove_volttron_service|default(false)|bool
      delay: 2
      retries: 3
    - name: Remove firebaseproxy.service if exists
      become: true
      become_method: sudo
      file:
        path: /etc/systemd/system/firebaseproxy.service
        state: absent
      when: remove_firebaseproxy_service|default(false)|bool
      delay: 2
      retries: 3
    - name: Creates ~/alto_run/Tools directory
      file:
        path: ~/alto_run/Tools
        state: directory
      delay: 2
      retries: 3
    - name: Creates ~/alto_run/system directory
      file:
        path: ~/alto_run/system
        state: directory
      delay: 2
      retries: 3
    - name: Creates ~/alto_run/examples directory
      file:
        path: ~/alto_run/examples
        state: directory
      delay: 2
      retries: 3
    - name: Copy Tools/firebase-proxy.py
      copy:
        src: "{{ ans_root_path }}/alto_os/Tools/firebase-proxy.py"
        dest: ~/alto_run/Tools/firebase-proxy.py
        mode: +x
      delay: 2
      retries: 3
    - name: Copy system/run-volttron
      copy:
        src: "{{ ans_root_path }}/alto_os/system/run-volttron"
        dest: ~/alto_run/system/run-volttron
        mode: +x
        # src: "{{ ans_root_path }}/alto_os/system"
        # dest: ~/alto_run
      delay: 2
      retries: 3
    - name: Copy system/run-firebaseproxy
      copy:
        src: "{{ ans_root_path }}/alto_os/system/run-firebaseproxy"
        dest: ~/alto_run/system/run-firebaseproxy
        mode: +x
      delay: 2
      retries: 3
    - name: Copy examples/rotatinglog.py
      copy:
        src: "{{ ans_root_path }}/alto_os/examples/rotatinglog.py"
        dest: ~/alto_run/examples/rotatinglog.py
      delay: 2
      retries: 3
    - name: Copy ~/alto_run/Tools/volttron-start-systemd
      become: true
      become_method: sudo
      copy:
        src: "{{ ans_root_path }}/alto_os/Tools/volttron-start-systemd"
        dest: /etc/systemd/system/volttron.service
        mode: +x
      delay: 2
      retries: 3
    - name: Copy ~/alto_run/Tools/firebase-start-systemd
      become: true
      become_method: sudo
      copy:
        src: "{{ ans_root_path }}/alto_os/Tools/firebase-start-systemd"
        dest: /etc/systemd/system/firebaseproxy.service
        mode: +x
      delay: 2
      retries: 3
    - name: Stop volttron.service
      become: true
      become_method: sudo
      systemd:
        state: stopped
        name: volttron
      delay: 2
      retries: 3
    - name: Stop firebaseproxy.service
      become: true
      become_method: sudo
      systemd:
        state: stopped
        name: firebaseproxy
      delay: 2
      retries: 3
    - name: Start volttron.service
      become: true
      become_method: sudo
      systemd:
        state: started
        name: volttron
        daemon_reload: yes
        enabled: yes
      delay: 2
      retries: 3
    - name: Start firebaseproxy.service
      become: true
      become_method: sudo
      systemd:
        state: started
        name: firebaseproxy
        daemon_reload: yes
        enabled: yes
      delay: 2
      retries: 3
