---
- name: Alto Crons
  hosts: test_ansible_1
  become: false
  vars:
    remove_alto_cron: true
    alto_user: alto
    script_list:
      cron_1:
        script_path: /Users/oenlighteno/Documents/Alto2021/ansible/mintel/alto_os/system/restart_with_memory_conditions/restart_with_memory_conditions.py
        config_path: /Users/oenlighteno/Documents/Alto2021/ansible/mintel/mintel_1_config/restart_with_memory_conditions.cron_1.json
        script_path_at_gateway: ~/alto_cron/restart_with_memory_conditions.py
        config_path_at_gateway: ~/alto_cron/restart_with_memory_conditions
        minute: "0"
        hour: "5"
      cron_2:
        script_path: /Users/oenlighteno/Documents/Alto2021/ansible/mintel/alto_os/system/restart_with_memory_conditions/restart_with_memory_conditions.py
        config_path: /Users/oenlighteno/Documents/Alto2021/ansible/mintel/mintel_1_config/restart_with_memory_conditions.cron_2.json
        script_path_at_gateway: ~/alto_cron/restart_with_memory_conditions.py
        config_path_at_gateway: ~/alto_cron/restart_with_memory_conditions
        minute: "0"
        hour: "*/3"
  tasks:
    - name: Remove alto_cron if exists
      file:
        path: ~/alto_cron
        state: absent
      when: remove_alto_cron|default(false)|bool
      delay: 2
      retries: 3
    - name: Creates ~/alto_cron directory
      file:
        path: ~/alto_cron
        state: directory
      delay: 2
      retries: 3
    - name: Copy venv_exec
      template: src=venv_exec.j2 dest=~/env_exec mode=755
      delay: 2
      retries: 3

    - name: Copy Scripts
      copy:
        src: "{{ item.value.script_path }}"
        dest: "{{ item.value.script_path_at_gateway }}"
      with_dict: "{{ script_list }}"
      delay: 2
      retries: 3
    - name: Copy Configs
      copy:
        src: "{{ item.value.config_path }}"
        dest: "{{ item.value.config_path_at_gateway }}.{{ item.key }}.json"
      with_dict: "{{ script_list }}"
      delay: 2
      retries: 3

    - name: "Removes a cron file from under /etc/cron.d"
      become: true
      become_method: sudo
      ansible.builtin.cron:
        name: "alto_script_{{ item.key }}"
        cron_file: "alto_cron_file_{{ item.key }}"
        state: absent
      with_dict: "{{ script_list }}"
      delay: 2
      retries: 3

    - name: Creates a cron file under /etc/cron.d
      become: true
      become_method: sudo
      ansible.builtin.cron:
        name: "alto_script_{{ item.key }}"
        minute: "{{ item.value.minute }}"
        hour: "{{ item.value.hour }}"
        user: "{{ alto_user }}"
        job: "~/env_exec ~/volttron/env/bin/python {{ item.value.script_path_at_gateway }} -c {{ item.value.config_path_at_gateway }}.{{ item.key }}.json"
        cron_file: "alto_cron_file_{{ item.key }}"
      with_dict: "{{ script_list }}"
      delay: 2
      retries: 3

