---
- name: Alto CrateDB Table
  hosts: test_ansible_1
  become: false
  vars:
    is_volttron_env: true
    alto_user: alto
    cratedb_listen_port: 4200
    cratedb_table_name: ananda
    crate_create_table_src_path: /Users/oenlighteno/Documents/Alto2021/ansible/bgrimm/config/crate_create_table.py.j2
    crate_create_table_dst_path: ~/crate_create_table.py
    crate_select_from_table_src_path: /Users/oenlighteno/Documents/Alto2021/ansible/bgrimm/config/crate_select_from_table.py.j2
    crate_select_from_table_dst_path: ~/crate_select_from_table.py
    crate_insert_into_table_src_path: /Users/oenlighteno/Documents/Alto2021/ansible/bgrimm/config/crate_insert_into_table.py.j2
    crate_insert_into_table_dst_path: ~/crate_insert_into_table.py
  tasks:
    - name: Copy venv_exec
      template: src=venv_exec.j2 dest=~/env_exec mode=755
      delay: 2
      retries: 3

    - name: Copy crate_create_table.py template to dst
      template:
        src: "{{ crate_create_table_src_path }}"
        dest: "{{ crate_create_table_dst_path }}"
        force: true
      delay: 2
      retries: 3
    - name: Copy crate_select_from_table.py template to dst
      template:
        src: "{{ crate_select_from_table_src_path }}"
        dest: "{{ crate_select_from_table_dst_path }}"
        force: true
      delay: 2
      retries: 3
    - name: Copy crate_insert_into_table.py template to dst
      template:
        src: "{{ crate_insert_into_table_src_path }}"
        dest: "{{ crate_insert_into_table_dst_path }}"
        force: true
      delay: 2
      retries: 3

    - name: Create table
      command: "~/env_exec python ~/crate_create_table.py"
      when: is_volttron_env|default(false)|bool
      delay: 2
      retries: 3
    - name: Select table
      command: "~/env_exec python ~/crate_select_from_table.py"
      register: res_log
      when: is_volttron_env|default(false)|bool
      delay: 2
      retries: 3
    - debug: var=res_log
    - name: Insert table
      command: "~/env_exec python ~/crate_insert_into_table.py"
      when: is_volttron_env|default(false)|bool
      delay: 2
      retries: 3
    - name: Select table
      command: "~/env_exec python ~/crate_select_from_table.py"
      register: res_log
      when: is_volttron_env|default(false)|bool
      delay: 2
      retries: 3
    - debug: var=res_log

    - name: Create table
      command: "python3 ~/crate_create_table.py"
      when: not is_volttron_env|default(false)|bool
      delay: 2
      retries: 3
    - name: Select table
      command: "python3 ~/crate_select_from_table.py"
      register: res_log
      when: not is_volttron_env|default(false)|bool
      delay: 2
      retries: 3
    - debug: var=res_log
    - name: Insert table
      command: "python3 ~/crate_insert_into_table.py"
      when: not is_volttron_env|default(false)|bool
      delay: 2
      retries: 3
    - name: Select table
      command: "python3 ~/crate_select_from_table.py"
      register: res_log
      when: not is_volttron_env|default(false)|bool
      delay: 2
      retries: 3
    - debug: var=res_log

    - name: Remove venv_exec if exists
      file:
        path: ~/env_exec
        state: absent
      delay: 2
      retries: 3
    - name: Remove crate_create_table if exists
      file:
        path: "{{ crate_create_table_dst_path }}"
        state: absent
      delay: 2
      retries: 3
    - name: Remove crate_select_from_table if exists
      file:
        path: "{{ crate_select_from_table_dst_path }}"
        state: absent
      delay: 2
      retries: 3
    - name: Remove crate_insert_into_table if exists
      file:
        path: "{{ crate_insert_into_table_dst_path }}"
        state: absent
      delay: 2
      retries: 3






