---
- name: Alto OS
  hosts: test_ansible_1
  become: false
  vars:
    ans_root_path: /Users/oenlighteno/Documents/Alto2021/ansible/beta
  tasks:
    - name: Copy alto_os libraries
      copy:
        src: "{{ ans_root_path }}/alto_os/libraries"
        dest: ~/alto_libraries
      delay: 2
      retries: 3
    - name: Install altolib
      command: "chdir=~/alto_libraries/libraries/altolib /home/alto/volttron/env/bin/python setup.py install"
      delay: 2
      retries: 3
    - name: Install altoutils
      command: "chdir=~/alto_libraries/libraries/altoutils /home/alto/volttron/env/bin/python setup.py install"
      delay: 2
      retries: 3
    - name: Install irgen
      command: "chdir=~/alto_libraries/libraries/irgen /home/alto/volttron/env/bin/python setup.py install"
      delay: 2
      retries: 3
    - name: Install python-broadlink
      command: "chdir=~/alto_libraries/libraries/python-broadlink /home/alto/volttron/env/bin/python setup.py install"
      delay: 2
      retries: 3
    - name: Remove alto_os libraries
      command: "rm -rf ~/alto_libraries"
      delay: 2
      retries: 3
