---
- name: Remove .volttron
  hosts: test_ansible_1
  become: false
  vars:
    remove_volttron: true
    stop_systemd_service: false
  tasks:
    - name: Stop volttron.service
      become: true
      become_method: sudo
      systemd:
        state: stopped
        name: volttron
      when: stop_systemd_service|default(false)|bool
      delay: 2
      retries: 3
    - name: Stop firebaseproxy.service
      become: true
      become_method: sudo
      systemd:
        state: stopped
        name: firebaseproxy
      when: stop_systemd_service|default(false)|bool
      delay: 2
      retries: 3
    - name: Remove .remove_volttron if exists
      file:
        path: ~/.volttron
        state: absent
      when: remove_volttron|default(false)|bool
      delay: 2
      retries: 3
