---
- name: Volttron Deps
  hosts: test_ansible_1
  tasks:
    - name: Update OS
      become: true
      become_method: sudo
      apt:
        # upgrade: yes
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 86400 #One day
      # until: result|succeeded
      delay: 2
      retries: 3
    - name: Install build-essential
      become: true
      become_method: sudo
      apt: name=build-essential state=present
      # register: apt_status
      # until: result|succeeded
      delay: 2
      retries: 3
    - name: Install python3-dev
      become: true
      become_method: sudo
      apt: name=python3-dev state=present
      # register: apt_status
      # until: result|succeeded
      delay: 2
      retries: 3
    # - debug: var=apt_status.stdout_lines
    - name: Install python3-venv
      become: true
      become_method: sudo
      apt: name=python3-venv state=present
      delay: 2
      retries: 3
    - name: Install openssl
      become: true
      become_method: sudo
      apt: name=openssl state=present
      delay: 2
      retries: 3
    - name: Install libssl-dev
      become: true
      become_method: sudo
      apt: name=libssl-dev state=present
      delay: 2
      retries: 3
    - name: Install libevent-dev
      become: true
      become_method: sudo
      apt: name=libevent-dev state=present
      delay: 2
      retries: 3
    - name: Install git
      become: true
      become_method: sudo
      apt: name=git state=present
      delay: 2
      retries: 3
